"""Default ordered channel names used to bootstrap the main group on first run.

This list is the same as sort_playlist_osnovnoe.py's DEFAULT_ORDERED_NAMES.
"""

from __future__ import annotations

DEFAULT_ORDERED_NAMES: tuple[str, ...] = (
    "Первый канал HD",
    "Первый канал +4 HD",
    "Россия 1 HD",
    "ТВЦ HD",
    "НТВ HD",
    "СТС HD",
    "ТНТ HD",
    "РЕН ТВ HD",
    "Пятница! HD",
    "Суббота! HD",
    "ТВ-3 HD",
    "Россия 24",
    "Москва 24",
    "360 Новости HD",
    "РБК HD",
    "Дождь HD",
    "Discovery Channel HD",
    "BOX Be On Edge HD",
    "BOX Be On Edge Live 1 HD",
    "BOX Be On Edge Live 2 HD",
    "Матч ТВ HD",
    "Eurosport 1 HD",
    "Eurosport 2 HD",
    "Окко Спорт HD",
    "Окко Прайм Спорт",
    "Окко Футбол HD",
    "Матч! Премьер HD",
    "Матч! Футбол 1 HD",
    "Матч! Футбол 2 HD",
    "Матч! Футбол 3 HD",
    "Sky Sport Premier League HD DE",
    "Sky Sport Bundesliga 1 HD DE",
    "Sky Sports Football HD UK",
    "Setanta Sports 1 HD",
    "Setanta Sports 2 HD",
    "Матч! Игра HD",
    "Матч! Арена HD",
    "Авто Плюс HD",
    "Liberty Авто Гир FHD",
    "BOX AutoTrend HD",
    "Драйв HD",
    "Fox Racing US",
    "Sky Sports Racing HD UK",
    "Sky Sports F1 HD UK",
    "DAZN F1 ES",
    "Sky Sport MotoGP HD IT",
    "Viju+ Sport HD",
    "Старт HD",
    "VHS-ка HD",
    "VF VHS MIX",
    "CineMan VHS",
    "VB VHS Classic",
    "Yosso TV VHS",
    "Fresh VHS",
    "KLI VHS HD",
    "Magic VHS HD",
    "StrahTV VHS HD",
    "BCU VHS HD",
    "MM NewFilm RU HD",
    "MM NewFilm 1 HD",
    "MM NewFilm 2 HD",
    "MM NewFilm 3 HD",
    "MM 007 HD",
    "MM Спорт HD",
    "KinoJam 1 HD",
    "KinoJam 2 HD",
    "Viju TV1000 HD",
    "Viju TV1000 Action HD",
    "Viju TV1000 Русское HD",
    "Viju+ Premiere HD",
    "Viju+ Megahit HD",
    "Viju+ Comedy HD",
    "Viasat Kino Megahit HD",
    "BCU Premiere HD",
    "BCU Premiere 2 HD",
    "BCU Premiere 3 HD",
    "VF Premiere",
    "VF Премьера",
    "Кинохит HD",
    "Киномикс HD",
    "Премиальное HD",
    "Kinoshka Premiere HD",
    "Кино ТВ HD",
    "MM Live Planet HD",
    "National Geographic HD",
    "Nat Geo Wild HD",
    "Animal Planet HD",
    "Liberty Планета360 FHD",
    "Big Planet HD",
    "Z!Travel HD",
    "Поехали! HD",
    "BOX Travel Premiere HD",
    "Travel Channel HD",
    "Охотник и Рыболов HD",
    "Дикая рыбалка HD",
    "Рыболов HD",
    "VF Рыбалка",
)
